"""add designers presence

Revision ID: 02cdcc69cac6
Revises: f114132e4d95
Create Date: 2026-09-17 03:38:53.336687

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02cdcc69cac6"
down_revision: Union[str, Sequence[str], None] = "f114132e4d95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "users",
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_online",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_online")
    op.drop_column("users", "last_activity_at")
    op.drop_column("users", "last_login_at")
    # ### end Alembic commands ###
