"""extend task comments for attachments

Revision ID: 111ff01f5b81
Revises: 692220224843
Create Date: 2026-08-31 07:23:30.361634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111ff01f5b81'
down_revision: Union[str, Sequence[str], None] = '692220224843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_comments', sa.Column('attachment_url', sa.Text(), nullable=True))
    op.add_column('task_comments', sa.Column('attachment_name', sa.String(length=255), nullable=True))
    op.add_column('task_comments', sa.Column('attachment_type', sa.String(length=100), nullable=True))
    op.add_column('task_comments', sa.Column('attachment_public_id', sa.String(length=255), nullable=True))
    op.add_column('task_comments', sa.Column('is_revision_request', sa.Boolean(), nullable=False))
    op.alter_column('task_comments', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_task_comments_user_id'), 'task_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_comments_user_id'), table_name='task_comments')
    op.alter_column('task_comments', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('task_comments', 'is_revision_request')
    op.drop_column('task_comments', 'attachment_public_id')
    op.drop_column('task_comments', 'attachment_type')
    op.drop_column('task_comments', 'attachment_name')
    op.drop_column('task_comments', 'attachment_url')
    # ### end Alembic commands ###
