"""extend task comments for attachments

Revision ID: 184547554a62
Revises: 111ff01f5b81
Create Date: 2026-09-01 03:52:28.591984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184547554a62'
down_revision: Union[str, Sequence[str], None] = '111ff01f5b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_comments', sa.Column('is_approval', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_comments', 'is_approval')
    # ### end Alembic commands ###
