"""add due date to orders

Revision ID: 347e4708ff49
Revises: fb6adeeba049
Create Date: 2026-09-09 14:40:08.505717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347e4708ff49'
down_revision: Union[str, Sequence[str], None] = 'fb6adeeba049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('due_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_orders_due_date'), 'orders', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_due_date'), table_name='orders')
    op.drop_column('orders', 'due_date')
    # ### end Alembic commands ###
