"""remove redundant payment/invoice logic

Revision ID: 39f7ffa113bf
Revises: 347e4708ff49
Create Date: 2026-09-10 05:12:55.744756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f7ffa113bf'
down_revision: Union[str, Sequence[str], None] = '347e4708ff49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('invoice_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'invoices', ['invoice_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_column('payments', 'invoice_id')
    # ### end Alembic commands ###
