"""add completed_at to orders

Revision ID: 40ae22a3ae10
Revises: 8d640078660d
Create Date: 2026-09-21 11:31:59.043376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ae22a3ae10'
down_revision: Union[str, Sequence[str], None] = '8d640078660d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_orders_completed_at'), 'orders', ['completed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_completed_at'), table_name='orders')
    op.drop_column('orders', 'completed_at')
    # ### end Alembic commands ###
