"""add designer charge to tasks

Revision ID: 4f6d86472b05
Revises: 40ae22a3ae10
Create Date: 2026-09-21 13:58:49.934737

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f6d86472b05"
down_revision: Union[str, Sequence[str], None] = "40ae22a3ae10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "designer_charge",
            sa.Numeric(12, 2),
            nullable=False,
            server_default="0.00",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "designer_charge")
    # ### end Alembic commands ###
