"""add production models

Revision ID: 624947761d78
Revises: 44fd77cc88b9
Create Date: 2026-08-31 06:37:45.677665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624947761d78'
down_revision: Union[str, Sequence[str], None] = '44fd77cc88b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_folders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('production_number', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'WAITING_FOR_REQUIREMENTS', 'READY_FOR_DESIGN', 'IN_DESIGN', 'DESIGN_REVIEW', 'APPROVED_FOR_PRINT', 'PRINTING', 'COMPLETED', 'CANCELLED', name='productionstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_folders_order_id'), 'production_folders', ['order_id'], unique=True)
    op.create_index(op.f('ix_production_folders_production_number'), 'production_folders', ['production_number'], unique=True)
    op.create_index(op.f('ix_production_folders_status'), 'production_folders', ['status'], unique=False)
    op.create_table('production_activities',
    sa.Column('production_folder_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_folder_id'], ['production_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_activities_production_folder_id'), 'production_activities', ['production_folder_id'], unique=False)
    op.create_index(op.f('ix_production_activities_user_id'), 'production_activities', ['user_id'], unique=False)
    op.create_table('production_files',
    sa.Column('production_folder_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_folder_id'], ['production_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_files_production_folder_id'), 'production_files', ['production_folder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_files_production_folder_id'), table_name='production_files')
    op.drop_table('production_files')
    op.drop_index(op.f('ix_production_activities_user_id'), table_name='production_activities')
    op.drop_index(op.f('ix_production_activities_production_folder_id'), table_name='production_activities')
    op.drop_table('production_activities')
    op.drop_index(op.f('ix_production_folders_status'), table_name='production_folders')
    op.drop_index(op.f('ix_production_folders_production_number'), table_name='production_folders')
    op.drop_index(op.f('ix_production_folders_order_id'), table_name='production_folders')
    op.drop_table('production_folders')
    # ### end Alembic commands ###
