"""add print order material requirements and inventory order history

Revision ID: 8d640078660d
Revises: f4d20d48e51e
Create Date: 2026-09-19 18:19:32.643558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d640078660d'
down_revision: Union[str, Sequence[str], None] = 'f4d20d48e51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_material_requirements',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.Column('consumed_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_material_requirements_inventory_item_id'), 'order_material_requirements', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_order_material_requirements_order_id'), 'order_material_requirements', ['order_id'], unique=False)
    op.add_column('stock_movements', sa.Column('order_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_stock_movements_order_id'), 'stock_movements', ['order_id'], unique=False)
    op.create_foreign_key(None, 'stock_movements', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_order_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'order_id')
    op.drop_index(op.f('ix_order_material_requirements_order_id'), table_name='order_material_requirements')
    op.drop_index(op.f('ix_order_material_requirements_inventory_item_id'), table_name='order_material_requirements')
    op.drop_table('order_material_requirements')
    # ### end Alembic commands ###
